CREATE DATABASE hospital;

CREATE TABLE medical_histories (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    admitted_at TIMESTAMP,
    patient_id INT,
    status VARCHAR,
    PRIMARY KEY(id)
);

CREATE TABLE patients (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR,
    date_of_birth DATE,
    PRIMARY KEY(id)
);

CREATE TABLE invoices (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    total_amount DECIMAL,
    generated_at TIMESTAMP,
    payed_at TIMESTAMP,
    medical_history_id INT,
    PRIMARY KEY(id)
);

CREATE TABLE invoice_items (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    unit_price DECIMAL,
    quantity INT,
    total_price DECIMAL,
    invoice_id INT,
    treatment_id INT,
    PRIMARY KEY(id)
);

CREATE TABLE treatments (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR,
    name VARCHAR,
    PRIMARY KEY(id)
);

CREATE TABLE treatments_history (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    medical_history_id INT,
    treatment_id INT,
    PRIMARY KEY(id)
);